### ISSUE TITLE
your app for f-droid

### ISSUE THREAD

**Issue by theScrabi** [SimonSchubert/LinuxCommandLibrary#3]
Hello,

since your App is free software, and seem to not have any bindings to nonfree libraries, you could easily promote it to pecome part of the f-droid repository. 
https://f-droid.org/

rgds schabi

**Comment by theScrabi** [comment]
I could write a f-droid buildscript for you, but in order to do that youd have to tag new releases.

**Comment by theScrabi** [comment]
No to pure :( U use app index, therefore no support for fdroid. Please consider a FLOSS version without com.google.android.gms:play-services-appindexin, also no commins.io would be helpfull if you realy wanted to push on f-droid.

**Comment by SimonSchubert** [comment]
Thank you for the interest, if I get the time at some point I will do it.

**Comment by theScrabi** [comment]
I can help you create the f-droid build script, but in order to do that, you might have to get rid of some libraries:
* play-services-appindexing will definetly not work
* org.apache.commons:commons-io might cause trouble

as I said, please consider an F-droid fork. The rest can be done by me.

**Comment by Poussinou** [comment]
This app on fdroid would be something awesome!

**Comment by SimonSchubert** [comment]
@theScrabi Sorry that that it took such a long time(3 years..) to get back to this issue.

But finally I managed to remove the google play services, even without a special f-droid fork. Since my goal is to make the app even more lightweight and performant. 

Could you have a look again if the current state of the master branch compliance with the f-droid guidelines?

**Comment by Poussinou** [comment]
I'm not sure we support build.gradle.kts [yet](https://gitlab.com/fdroid/fdroidserver/issues/613).

Could you rollback to the good old build.gradle ?

**Comment by SimonSchubert** [comment]
In may we successfully released(https://gitlab.com/fdroid/rfp/issues/931#note_168935002) my other app on an f-droid private repo(https://apt.izzysoft.de/fdroid/index/apk/com.inspiredandroid.newsout). It was build with gradle.kts, so I think and hope it is fully supported. :) Since I would like to avoid to rollback.

**Comment by IzzySoft** [comment]
Just found the last notification while cleaning up my mail: looks like `.kts` is supported now. So maybe your RFP is faster than your APK here :speak_no_evil:

**Comment by Lonerider2010** [comment]
What is the current status of this project in F-Droid?

**Comment by IzzySoft** [comment]
There was [an RFP opened](https://gitlab.com/fdroid/rfp/-/issues/1494) yesterday. The bot check returned green, but it would be nice if @SimonSchubert could establish [Fastlane structures](https://gitlab.com/snippets/1895688) here in the app's repo (details behind the link; mainly for screenshots and so summary/description etc. can be maintained with the app itself). Double value: the very same can be used to publish to Play, if wanted.

**Comment by IzzySoft** [comment]
The RFP is still stalled waiting for Fastlane structures (at least `short_description.txt` and `full_description.txt` for `en-US`, all else is optional though screenshots would be a very good idea as well). @SimonSchubert any chance we get this running?

**Comment by SimonSchubert** [comment]
Hey @IzzySoft sorry I hadn't maintained the project for a while.  I've reworked all the source code and added a bunch of new content recently.

Is the bot still returning green and do I only need to set up the fastlane files?

**Comment by IzzySoft** [comment]
The RFP has meanwhile be closed for inactivity. But if you'd setup Fastlane here (just need to merge #5 :smiley:) and explicitly add a license (if I read the code correctly, it seems to be Apache-2.0?), be welcome to give me a ping when it's ready and we can see to reopen it and pick up again.

PS: It would be a good idea if you can get the tag names in sync with your versioning. So the current tag should be either `69` (corresponding to the `versionCode`)  or `3.0.0` (corresponding to the `versionName`). the `4` is a bit irritating and makes matching hard.

For starters, I've just added your app to my repo, so it should [show up here](https://apt.izzysoft.de/fdroid/index/apk/com.inspiredandroid.linuxcommandbibliotheca) with the next sync around 6 pm UTC.

**Comment by SimonSchubert** [comment]
You even made the effort to create a PR with all the necessary info and kept you in the dark for 2 years. Apologize!

Will be epic to close the 6 years old issue.

The `4` on the releases page automatically increments, now it's `5` because of the PR merge. New debug release will get created with github actions every time a push to `master` branch happens. I'm not to familiar with github actions but I will see what I can do.

Just on thing, also regarding your repo. The `database.db` is currently missing in the project because I was unsure about the licencing. All my code is licensed under Apache-2.0 correct. But what if man pages are licensed under a different license? Is it enough to write something like `All man pages are copyrighted by their respective authors` in the README.md?

**Comment by SimonSchubert** [comment]
Please let me know if there is an issue with the updated `full_description.txt` and `short_description.txt`. I have created a script to automatically build the files with information from the current state of the database. [desktop/src/jvmMain/kotlin/FdroiInfoBuilder.k](https://github.com/SimonSchubert/LinuxCommandLibrary/blob/master/desktop/src/jvmMain/kotlin/FdroiInfoBuilder.kt) 

`database.db` and license info with respect to the man page authors is also back in. I have not encountered a non-free license in the man pages but I cannot guarantee that there is none. So a `NonFreeAssets` will be needed for now.

Last but not least I will dig into the `versionCode` for the release now

**Comment by IzzySoft** [comment]
> Please let me know if there is an issue with the updated `full_description.txt` and `short_description.txt`.

They look both excellent, thanks!

> `NonFreeAssets` will be needed for now.

Full ack. And "in good trust" I'd not expect a Linux man page to be non-free :smile:

> Yeeeaaah the Github action finally seems to work properly

Congrats! :tada: I've just pinned update checking to `v<versionName>` then. So if there's some tag you don't want my updater to pick up, just name it differently (omitting the leading `v` or replacing it by something else suffices to let the updater skip it – useful if you want to place some testing APK that should not be spread widely, or some different build variant).

> Do you want me to sign the apk with the same key I used in the Play Store or different key?

Up to you. I'd suggest going with the same key, as that makes it easier for existing users to switch over (or even cross-update if for one reason or another one side misses updates – most likely Play due to some crazy G-stuff, see e.g. [Your app is not compliant with Google Play Policies: A story from hell](https://sylviavanos.nl/blog/2021/12/24/google_play_hell.html) – or a misnamed tag leading to my updater failing).

----

That said: all looks very fine now, and I see no show-stoppers bringing your app to F-Droid.org's own repo. Let me know if you want to go that path again; being one of the maintainers there, I could then reopen the [existing RFP](https://gitlab.com/fdroid/rfp/-/issues/1494) to be picked up again, or you could open a new one if you prefer.

**Comment by SimonSchubert** [comment]
> Full ack. And "in good trust" I'd not expect a Linux man page to be non-free 😄

Exactly 😀 if I find a way to verify that I will let you know

> Congrats! 🎉 I've just pinned update checking to v<versionName> then

Perfect

> being one of the maintainers there, I could then reopen the existing RFP

Yes please reopen. I would love to see the app in the main repo. 

I will sign v3.0.1 with the Play Store Release key. And I agree, it will be a better experience for the user. Google might also warn users if they try to install an app with a package name which is on their store but signed with a different key.

Please let me know what else you will need for the RFP.

**Comment by SimonSchubert** [comment]
The F-Droid Bot results look good I guess. Just 2 things I noticed: bot lists the project dependencies twice and `desktop/build.gradle.kts` dependencies are not used for the mobile app. Only `android/build.gradle.kts` and `common/build.gradle.kts`

![image](https://user-images.githubusercontent.com/1833337/177700521-26334004-5fd5-4c91-9c6f-a73de9193a4e.png)

But I don't think those are either showbreakers, are they?

Also, v3.0.1 is released and signed with the Play Store Release key.

**Comment by IzzySoft** [comment]
That's no stopper, no. The bot at RFP only nows the repo to scan, not the subdirs it should use or ignore. Once the merge request at fdroiddata is set up (you can do that yourself, I posted the contents and the name of the YAML file), the bot gets precise instructions (see the `Builds` block) and only will scan what it's told to.

v3.0.1 should be picked up automatically by my updater then. Should you open said MR yourself, you can adjust the build block accordingly (at F-Droid, we always start with the latest version only).

**Comment by licaon-kter** [comment]
For the future do add `changelogs/<versionCode>.txt` here https://github.com/SimonSchubert/LinuxCommandLibrary/tree/master/fastlane/metadata/android/en-US

FYI, https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11309

**Comment by IzzySoft** [comment]
@SimonSchubert please rename the changelogs as indicated above: `<versionCode>.txt`, not `<versionName>.txt`. Else they are not found/matched.

**Comment by IzzySoft** [comment]
Already used with my repo (I pulled and renamed it manually).

**Comment by SimonSchubert** [comment]
Yeeeeeees

![Screenshot_20220711-222707](https://user-images.githubusercontent.com/1833337/178352242-c37e704e-bca3-4f75-92d5-44d292861900.png)

Just the feature graphic isn't showing
https://github.com/SimonSchubert/LinuxCommandLibrary/blob/master/fastlane/metadata/android/en-US/images/featureGraphic.png

**Comment by SimonSchubert** [comment]
Ohh nevermind. Feature graphic is showing. Thanks a lot to everyone especially @IzzySoft 

6 years old issue will finally be closed

**Comment by IzzySoft** [comment]
Congrats! So shall I still keep your app in my repo then? Usually I remove apps at this stage (after an overlap of about 10 days so people get their F-Droid clients synced) unless explicitly requested otherwise (see [here](https://gitlab.com/IzzyOnDroid/repo/-/wikis/FAQ) for some background).

**Comment by SimonSchubert** [comment]
@IzzySoft Good question, to keep it in your repo really has some advantages. Don't know how relevant it would be in this apps case. I guess you could remove it after the 10 days. And if there might be a reason in the future it would be easy to add it back to your repo right?

**Comment by IzzySoft** [comment]
That's correct. "Removing" basically means I archive the metadata (the `*.yml` file) and remove the APKs plus Fastlane structure. So re-establishing is as easy as moving the YAML back into place, pick the latest APK, and then have all else automatically fetched from Fastlane.

As for "relevance": if you plan frequent updates, this might wight in (as updates with my repo are available within 24h while F-Droid takes several days). But I don't think that will be the case. There are neither different builds – so we should be fine with archiving.

I'll put a mark now that once it's reported for removal you've confirmed that – and should you change your mind you let me know and we either cancel archiving (when in time) or re-establish the app. Thanks!

**Comment by licaon-kter** [comment]
```
ERROR: Found unknown maven repo 'https://maven.pkg.jetbrains.space/public/p/compose/dev' at settings.gradle.kts
ERROR: Could not build app com.inspiredandroid.linuxcommandbibliotheca: Can't build due to 1 error while scanning
```
ref: https://github.com/SimonSchubert/LinuxCommandLibrary/commit/91badc8ca77b381d97d766f7c26ad13b30744ccb#diff-5625e3601fa0ad3a6a2824239e5a2fde71c149597d31394f9224a08c24be7b9dR7

**Comment by SimonSchubert** [comment]
Thanks for pointing that out. I removed the outdated repo in the latest commit

**Comment by SimonSchubert** [comment]
@IzzySoft the app has come a long way since we/you were able to get it on f-droid. Unfortunately recently the f-droid builds aren't published anymore because I did some changes to the gradle.kts would you mind to help me out or point me to the right direction?

**Comment by IzzySoft** [comment]
Thanks @licaon-kter ! And as you asked me, Simon, I've also taken a quick look. You should start thinking about a new signing key:

```
Signature algorithm name: SHA1withRSA (weak)
Subject Public Key Algorithm: 1024-bit RSA key (weak)
The certificate uses the SHA1withRSA signature algorithm which is considered a security risk. This algorithm will be disabled in a future update.
The certificate uses a 1024-bit RSA key which is considered a security risk. This key size will be disabled in a future update.
```

That is, for your own APKs – F-Droid uses a dedicated key they created themselves for your app. To avoid everyone having to uninstall/reinstall then, [Signing Key Rotation](https://web.archive.org/web/20241218183439/https://anandbose.dev/android-signing-key-rotation-explained/) is an option for Android 9 and higher.

**Comment by licaon-kter** [comment]
done: https://gitlab.com/fdroid/fdroiddata/-/commit/25e54c00aa8bafb732b63bdf42ea89ff0c9d7cf0
